In [1]:
import requests
import pandas as pd
from tqdm import tqdm
import tmdbdata as td

In [2]:
ids= td.get_movie_ids_list(1, headers=td.headers)
df=td.get_movies_info(ids,headers=td.headers)
df.head(3)

getting movie ids

100%|██████████| 1/1 [00:00<00:00,  1.85it/s]

getting movie info

100%|██████████| 20/20 [00:02<00:00,  8.48it/s]

,adult,backdrop_path,belongs_to_collection,budget,genres,homepage,id,imdb_id,origin_country,original_language,...,status,tagline,title,video,vote_average,vote_count,belongs_to_collection.id,belongs_to_collection.name,belongs_to_collection.poster_path,belongs_to_collection.backdrop_path
0,False,/bGksau9GGu0uJ8DJQ8DYc9JW5LM.jpg,None,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",,77338,tt1675434,[FR],fr,...,Released,Sometimes you have to reach into someone else'...,The Intouchables,False,8.3,17192,NaN,NaN,NaN,NaN
1,False,/6n53UI4mX9QMfe2S0Pgt8mGebY1.jpg,None,10000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",https://www.miramax.com/movie/amelie/,194,tt0211915,[FR],fr,...,Released,She’ll change your life.,Amélie,False,7.9,11484,NaN,NaN,NaN,NaN
2,False,/uuyC8vih50lyRKjxQ5FWjCF6hGN.jpg,None,4300000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",,152584,tt2278871,[FR],fr,...,Released,,Blue Is the Warmest Color,False,7.1,4553,NaN,NaN,NaN,NaN

In [3]:
df1=td.drop_useless_info(df)
df1=td.keep_main_genre(df1)
df1=td.full_poster_path(df1)

In [4]:
df1.head(3)

,budget,id,overview,popularity,release_date,revenue,runtime,title,vote_average,vote_count,main_genre_id,main_genre_name,full_poster_path
0,13000000,77338,A true story of two men who should never have ...,60.390,2011-11-02,426590315,113,The Intouchables,8.3,17192,18,Drama,https://image.tmdb.org/t/p/original//1QU7HKgsQ...
1,10000000,194,"At a tiny Parisian café, the adorable yet pain...",45.403,2001-04-25,173921954,122,Amélie,7.9,11484,35,Comedy,https://image.tmdb.org/t/p/original//6pMAiHi9w...
2,4300000,152584,"Adèle's life is changed when she meets Emma, a...",27.520,2013-10-09,19465835,180,Blue Is the Warmest Color,7.1,4553,10749,Romance,https://image.tmdb.org/t/p/original//kgUk1wti2...

In [5]:
df.to_csv('moviedata.csv')